version: '3.1'
services:
  db-example-04:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "4006:3306"
    container_name: db_example_04
    environment:
      MYSQL_ROOT_PASSWORD: "demo04"
      MYSQL_DATABASE: db_example
