const PUBLIC_ROUTE_PUBLIC_FOLDER = 'PUBLIC_ROUTE_PUBLIC_FOLDER'
const ROUTE = 'ROUTE'
const ROUTE_CONTEXT = 'ROUTE_CONTEXT'

module.exports = {
  PUBLIC_ROUTE_PUBLIC_FOLDER,
  ROUTE,
  ROUTE_CONTEXT
}
